### ISSUE TITLE
Cannot unlock bootloader on xiaomi devices. Chipset Dimensity 1080

### ISSUE THREAD

**Issue by UName122** [bkerler/mtkclient#1041]
So it says it is done, but when booting, it is not unlocked. Might have something to do with xiaomi authenticating even bootloaders with a serial number.

**Comment by pewterbrass** [comment]
Xiaomi has a custom bootloader lock implementation on top of the standard one using seccfg. That's why mtkclient says it's unlocked, but in reality the device is only half unlocked.

You need to connect your device to your Mi account and get an unlock token for it.

There is no easy way around this, even though it's probably technically possible.

**Comment by bkerler** [comment]
Exactly. MTK unlock implementation is not the same as Vendor unlock implementation, especially for vendors such as Xiaomi or Oppo or Vivo or Oneplus.
