### ISSUE TITLE
Flash official firmware

### ISSUE THREAD

**Issue by deyvs02** [bkerler/mtkclient#114]
is there possibility to flash using scatter from an official firmware using mtk-client?

**Comment by bkerler** [comment]
I will try to add padding as well for writing, so that no external tools are needed.

**Comment by etmatrix** [comment]
After I closed #84 I done many tests and I analyzed the code for implement padding but I see is already implemented.
So for now the only solution is read, overwrite without truncate and write, has never failed until now.
Before the issue #104 I thought which was only my issue.
Also my device is MT6739 as for issue #104 so I don't know the issue is on padding or other. 
2 times writing stuck at 0.0%

**Comment by mslhii** [comment]
> only manually.
> 
> * extract file from firmware
> * extract compressed file as lz4 or br
> * ./mtk w < partition > < partition file.img >
> 
> Sometime write partition got an error because there is an issue on padding, so you should read partition and copy the content of file in official firmware, in new extracted file, don't truncate the size. In linux I use `dd if=newfile.bin of=readpartition.bin conv=notrunc`

Can confirm I can't flash any patched Magisk boots to my TCL/Alcatel phones due to the padding issue

**Comment by deyvs02** [comment]
work
