### ISSUE TITLE
Waiting for PreLoader VCOM, please reconnect mobile to brom mode

### ISSUE THREAD

**Issue by pablocool** [bkerler/mtkclient#1156]
Hi

First of all thank you for this awsome tool. It works perfect on prebuilt Linux ISO. However I cannot make it to work in Windows 10. I am getting error "Waiting for PreLoader VCOM, please reconnect mobile to brom mode" or "Jumping to 0x200000: ok.". 

I've carefully followed your guide. I've also installed Preloader VCOM driver by adding legacy device from device menager.
What am I missing?
![mtkclient1a](https://github.com/user-attachments/assets/e7e4bcda-244d-471a-acff-25725f4611c9)
![mtkclient1](https://github.com/user-attachments/assets/93cd5436-45d9-4d33-ad66-bbbf21fc6a7f)
![mtkclient2](https://github.com/user-attachments/assets/ccb52359-a721-49b0-8421-f3f78e4dce44)

**Comment by bkerler** [comment]
The question mark indicates that you need to update the usbdk device driver after reconnecting. Otherwise, you might consider to use the --noreconnect option. Be aware that windows updates the usb stack quite often and usbdk seems not able to cope with updates, thus I recommend to use linux instead.
