### ISSUE TITLE
Can i read phone model and imei in brom mode

### ISSUE THREAD

**Issue by samuel1003** [bkerler/mtkclient#164]
I am willing to know if there is a way to read those usefull info when payload.

**Comment by bkerler** [comment]
For phone model, read system partition (default.prop). For imei read nvitems.

**Comment by samuel1003** [comment]
Wow, is there a direct command i could use? I can read system but it will last too long reading.

**Comment by bkerler** [comment]
None I know of, but I will have a look.

**Comment by etmatrix** [comment]
for read imei you should decrypt it from nvran/nvdata, there is this FR #100

**Comment by ferouzkassim** [comment]
Not certain because the imei and other data is in some partitions that need
to be mounted first so that u read the information from it partitions like
nvdata protect1 protect2 nvram e.t.c it also depends on the device's
customisation but you can aim for it if you anyway try to get succes kindly
post it here
