### ISSUE TITLE
Mt6765 Samsung a125u 

### ISSUE THREAD

**Issue by Warlockguitarman** [bkerler/mtkclient#188]
Doesn't unlock bootloader,  any suggestions?

**Comment by kushpr** [comment]
whats the firmware version on it ? @Warlockguitarman

**Comment by Warlockguitarman** [comment]
Android 10 A125USQS2AUF3

**Comment by kushpr** [comment]
:/ damn that sucks @Warlockguitarman 

have you any luck root the a326u on bit 4?

**Comment by Warlockguitarman** [comment]
I haven't had that model yet

**Comment by bkerler** [comment]
Support for samsung unlocking isn't planned right now.

**Comment by Warlockguitarman** [comment]
Well I'm gonna work on it,  I can share my process if I figure it out

**Comment by Warlockguitarman** [comment]
A few other guys and i have come to the conclusion the LK.img is holding back the unlock,  is missing a small line of code in the U model that is in the N and other models,  if there could be a hash code to flash the LK lines of code then it should unlock normally like the unlockable models

**Comment by PrizmJKR** [comment]
> :/ damn that sucks @Warlockguitarman
> 
> have you any luck root the a326u on bit 4?

Also have no luck on the MT6765 powered Galaxy A21, A215U / S215DL. I think patching in the needed missing code to the phone's LK will allow the bootloader to be unlocked.

**Comment by jamb84** [comment]
LK itself doesn't have a hash inside it. Seccfg works this way because it is not covered by the AVB config. The hash for LK is a salted hash stored in vbmeta. The U model LK has entire check function missing where it doesn't look at the seccfg and persistent partitions and compare the return code for unlock capability. Instead it bypasses this completely and has the comparison hardcoded for a return code of 0, but even then, the actual functions used for the checks are completely missing as well, not just the comparison. So, we would need to find a way to patch the comparison to a hardcoded return code of 1 which should allow the LK to display the option to unlock. I'm not sure what other patches would be necessary after that. After patching we would need a way to modify the vbmeta with the new hash to allow LK to pass AVB but this would require the correct hash to be generated - which i'm unfamiliar with the process for.
