### ISSUE TITLE
Phone not detected by MTKclient always shows error waiting for preloader

### ISSUE THREAD

**Issue by lmq730mm** [bkerler/mtkclient#228]
Phone not detected by MTKclient. The phone shows charging symbol when connected to computer.  
Always shows error - waiting for preloader VCOM Couldn't find CDC interface

![powershell error](https://user-images.githubusercontent.com/97777194/149610878-b5395a64-3365-4f21-8d25-80c2d85010ee.jpg)

**Comment by bkerler** [comment]
Clearly a windows driver issue. Make sure you have the right drivers and usbdk installed correctly.

**Comment by bkerler** [comment]
Please try commit b30d65c. Should be fixed. Sorry I thought it might be a windows error, it was clearly a bug.

**Comment by RenateUSB** [comment]
If it's showing a big battery icon it's probably presenting as 0e8d/20ff, an HID interface.

Questions (never to be answered):
Why MediaTek needs 0e8d/0003, 0e8d/2000, 0e8d/20ff?
Why MediaTek went with CDC instead of a bulk interface?

BTW, I can't get MTKclient to acknowledge my VCOM (Com5, MediaTek driver) on 0e8d/0003 either.

It's there. With a bit of my own code I can see it get some info and kill the WDT.
```Waiting...
Connected
Hardware 8168, version 0000
Config 000000e0
Read 0000004d
Read 00000064
Success
