### ISSUE TITLE
More information about patched Magisk

### ISSUE THREAD

**Issue by benthetechguy** [bkerler/mtkclient#394]
Is there more information available about this patched Magisk we are using? I would like to know what specifically is being patched and more importantly how I can patch and build my own Magisk.

**Comment by bkerler** [comment]
This is not related to mtkclient. Please ask this on the magisk repo.

**Comment by benthetechguy** [comment]
Could you at least explain to me why mtkclient requires a special version of Magisk?

**Comment by benthetechguy** [comment]
OK, thanks for the info.

**Comment by Chaoses-Ib** [comment]
In fact, from the URL of the patched Magisk you can find the corresponding commit here: https://github.com/vvb2060/magisk_files/commit/44ca9ed38c29e22fa276698f6c03bc1168df2c10. However, because that commit has been removed (GitHub says `This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.`), and the repository only contains APK, we still can't figure out what is patched. Maybe [the latest alpha branch](https://github.com/vvb2060/magisk_files/tree/alpha) is also avaiable, I dont' know. @vvb2060, can you provide some help?

**Comment by vvb2060** [comment]
All MTK related changes have been committed upstream.

**Comment by benthetechguy** [comment]
Alright, I'll make a PR to update the README to use normal Magisk.

**Comment by Chaoses-Ib** [comment]
Installed Magisk v25.1 on OPPO Reno6 (MT6877, ColorOS 11), works fine.
