### ISSUE TITLE
MT6853 SM-A326U

### ISSUE THREAD

**Issue by mtklover** [bkerler/mtkclient#427]
READ PARTBL FAILED 

i think your look into the wrong partition table

**Comment by macolodalis** [comment]
dear with mtkclient u wont will get this work, becasue this device are ufs and when enters to bootrom has partittions locked. can do everything but cannot erase or write.

BR

**Comment by jerryurenaa** [comment]
You can read the partition table as long as you did not damage the PGPT partition.  

I think you damaged the partition table while entering brom mode. 

To fix this flash the firmware preloader to the offset 0x000000 with length 0x400000. the phone will now reboot into download mode and then flash a full firmware to fix it.  

now you can open the phone and do test point like you normally would and try to read the table again. Should work :D

Please note that you would need to provide the correct preloader using the --preloader="preloader location" otherwise you will not be able to read the partition table.  

the correct preloader for this phone is called. preloader_k6853v1_64_titan 

MTK client has a weird bug while flashing UFS Samsung devices. just try using other tools to flash because it will not work here.

**Comment by bkerler** [comment]
The pgpt partition is only damaged when the format or erase or write option is being used incorrectly.
Samsung devices have write protection, that's no bug of mtkclient.
