### ISSUE TITLE
Stop creating "logs" dir and ".state" files in $PWD

### ISSUE THREAD

**Issue by JamiKettunen** [bkerler/mtkclient#438]
It's rather annoying having any and all directories my shell happens to be currently in when I run `mtk` getting a `logs` dir and `.state` file after execution.

**Comment by bkerler** [comment]
that's how the tool works and it is done intentionally.

**Comment by JamiKettunen** [comment]
Even leaving them after runtime is on purpose? just seems like temporary files that aren't being cleaned up. Wouldn't it make more sense to relocate this kind of things to `XDG_STATE_HOME` (e.g. `~/.local/state`)?

**Comment by bkerler** [comment]
The idea is to leave the state file in the current working directory. Some users are using multiple smartphones with individual states. The state file is no config, it's keeping track of the current device state. Not sure yet if XDG_STATE_HOME would be a better place or if there is a better way to handle the state. Most people don't use Linux but use Windows instead (some even use Mac), which doesn't have similar directories. Right now there are no plans to change the behaviour as otherwise all software that is based on mtkclient would need to be rewritten. The files are being cleaned up, but only if a specific state of the device is reached (reconnection after connection termination). It's not that I'm happy about it, but I don't see any other good way right now without introducing more issues.
