### ISSUE TITLE
DAXFlash - [LIB]: Error jumping to DA: -1

### ISSUE THREAD

**Issue by elevencupoftea** [bkerler/mtkclient#627]
After all commands ends with the same crash. Any ideas?
```Port - Device detected :)
Preloader - 	CPU:			MT6833(Dimensity 700 5G k6833)
Preloader - 	HW version:		0x0
Preloader - 	WDT:			0x10007000
Preloader - 	Uart:			0x11002000
Preloader - 	Brom payload addr:	0x100a00
Preloader - 	DA payload addr:	0x201000
Preloader - 	CQ_DMA addr:		0x10212000
Preloader - 	Var1:			0x73
Preloader - Disabling Watchdog...
Preloader - HW code:			0x989
Preloader - Target config:		0xe7
Preloader - 	SBC enabled:		True
Preloader - 	SLA enabled:		True
Preloader - 	DAA enabled:		True
Preloader - 	SWJTAG enabled:		True
Preloader - 	EPP_PARAM at 0x600 after EMMC_BOOT/SDMMC_BOOT:	False
Preloader - 	Root cert required:	False
Preloader - 	Mem read auth:		True
Preloader - 	Mem write auth:		True
Preloader - 	Cmd 0xC8 blocked:	True
Preloader - Get Target info
Preloader - BROM mode detected.
Preloader - 	HW subcode:		0x8a00
Preloader - 	HW Ver:			0xca00
Preloader - 	SW Ver:			0x0
Preloader - ME_ID:			600E3A539861536BCB5146B2D3B279AD
Preloader - SOC_ID:			7D1C066CAB13256FBB894CA96C42657014DC3CC7AAE453D1783881D01FB6C0D0
PLTools - Loading payload from mt6833_payload.bin, 0x264 bytes
PLTools - Kamakiri / DA Run
Kamakiri - Trying kamakiri2..
Kamakiri - Done sending payload...
PLTools - Successfully sent payload: /home/elevencupsoftea/android/mtkclient/mtkclient/payloads/mt6833_payload.bin
Port - Device detected :)
DA_handler - Device is protected.
DA_handler - Device is in BROM mode. Trying to dump preloader.
DAXFlash - Uploading xflash stage 1 from MTK_AllInOne_DA_5.2136.bin
xflashext - Patching da1 ...
Mtk - Patched "Patched loader msg" in preloader
xflashext
xflashext - [LIB]: **Error on patching da1 version check...**
Mtk - Patched "Patched loader msg" in preloader
Mtk - Patched "get_vfy_policy" in preloader
xflashext - Patching da2 ...
DAXFlash - Successfully uploaded stage 1, jumping ..
Preloader - Jumping to 0x200000
Preloader - Jumping to 0x200000: ok.
DAXFlash
DAXFlash - [LIB]: xread error: unpack requires a buffer of 12 bytes
DAXFlash
DAXFlash - [LIB]: Error jumping to DA: -1
```

**Comment by King12689** [comment]
why not reset everythig from start it happens to me after i did reset everything from start it works well now

**Comment by NeonzGamingYT** [comment]
> why not reset everythig from start it happens to me after i did reset everything from start it works well now

Reset what?

**Comment by King12689** [comment]
> > why not reset everythig from start it happens to me after i did reset everything from start it works well now
> 
> Reset what?

your installation of your mtk client start form the bottom it will fix everything like mine i always got that error until i reset all

**Comment by ndiranguW** [comment]
Have same error on Tecno device. Any info to solve?

**Comment by elevencupoftea** [comment]
> Have same error on Tecno device. Any info to solve?
The service center said that this is a hardware problem

**Comment by ndiranguW** [comment]
mmh, Okay. 
I went on searching for solutions and had a small advancement and got another error. 
what could it be? Kindlly assist.

--------........Port - Device detected :)
Preloader - 	CPU:			MT6761/MT6762/MT3369/MT8766B(Helio A20/P22/A22/A25/G25)
Preloader - 	HW version:		0x0
Preloader - 	WDT:			0x10007000
Preloader - 	Uart:			0x11002000
Preloader - 	Brom payload addr:	0x100a00
Preloader - 	DA payload addr:	0x201000
Preloader - 	CQ_DMA addr:		0x10212000
Preloader - 	Var1:			0x25
Preloader - Disabling Watchdog...
Preloader - HW code:			0x717
Preloader - Target config:		0xe5
Preloader - 	SBC enabled:		True
Preloader - 	SLA enabled:		False
Preloader - 	DAA enabled:		True
Preloader - 	SWJTAG enabled:		True
Preloader - 	EPP_PARAM at 0x600 after EMMC_BOOT/SDMMC_BOOT:	False
Preloader - 	Root cert required:	False
Preloader - 	Mem read auth:		True
Preloader - 	Mem write auth:		True
Preloader - 	Cmd 0xC8 blocked:	True
Preloader - Get Target info
Preloader - BROM mode detected.
Preloader - 	HW subcode:		0x8a00
Preloader - 	HW Ver:			0xca01
Preloader - 	SW Ver:			0x200
Preloader - ME_ID:			4A2AB2FA12F9A04F5A52FC3ADE78177C
Preloader - SOC_ID:			2B515D4C39898CA7E24626693E6F4CFFF86CC63D1C210279565434A28238D4D3
PLTools - Loading payload from mt6761_payload.bin, 0x264 bytes
PLTools - Kamakiri / DA Run
Kamakiri - Trying kamakiri2..
Kamakiri - Done sending payload...
PLTools - Successfully sent payload: /home/billy/share/droid_tools/mtkclient-main/mtkclient/payloads/mt6761_payload.bin
Port - Device detected :)
DA_handler - Device is protected.
DA_handler - Device is in BROM mode. Trying to dump preloader.
DAXFlash - Uploading xflash stage 1 from MTK_AllInOne_DA_5.2136.bin
xflashext - Patching da1 ...
Mtk - Patched "Patched loader msg" in preloader
xflashext
xflashext - [LIB]: Error on patching da1 version check...
Mtk - Patched "Patched loader msg" in preloader
Mtk - Patched "get_vfy_policy" in preloader
xflashext - Patching da2 ...
DAXFlash - Successfully uploaded stage 1, jumping ..
Preloader - Jumping to 0x200000
Preloader - Jumping to 0x200000: ok.
DAXFlash - Successfully received DA sync
DAXFlash - DRAM config needed for : 1501004355544134
DAXFlash - No preloader given. Searching for preloader
DAXFlash - Sending emi data ...
DAXFlash
DAXFlash - [LIB]: No preloader given. Operation may fail due to missing dram setup.
DAXFlash - Uploading stage 2...
DAXFlash
DAXFlash - [LIB]: Error on sending data: DA hash mismatch (0xc0070004)
DAXFlash
DAXFlash - [LIB]: Error on booting to da (xflash)

--------------

**Comment by miracule** [comment]
Maybe try putting the preloader in the mtkclient file? Like we do for boot.img
