### ISSUE TITLE
can anybody help me

### ISSUE THREAD

**Issue by Leotaku-senpai** [bkerler/mtkclient#877]
I have a hard brick in my poco m5 and I can't recover it if someone with a good heart can help me I would be grateful

**Comment by tadekdudek** [comment]
This device uses V6 protocol and auth, so there is no way to recover it without paying someone who has a service account.

PS. For things like bricked devices, use XDA instead of posting off-topic posts here... It's exactly what XDA is made for... so the chance of finding "someone with a good heart" is much higher than here. Not to mention that your post elsewhere is likely to be deleted without a reply...

**Comment by Leotaku-senpai** [comment]
sorry

**Comment by Leotaku-senpai** [comment]
Is there any way to disable the daa SLA when I fix my cell phone so if a hard brick happens again I can recover by flashing the boot.img

**Comment by embzhezh** [comment]
this is sad friends....

**Comment by bikesh1122** [comment]
Come on telegram so flashing low price. @Bikeshkumar6
